/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti.templates;

import java.util.*;

/**
 *
 * @author jon
 */
public class EmptyExam
        extends ExamTemplate
{
  public String getTemplateTitle() {return "Exam/Survey with no questions.";}
  
  public static final String text = "<?xml version=\"1.0\"?>\n" +
"<examination>\n" +
"\n" +
"\n" +
"<options>\n" +
"<option name=\"ignore_flow\">false</option>\n" +
"<option name=\"question_titles\">false</option>\n" +
"<option name=\"double_sided\">false</option>\n" +
"<option name=\"name_in_footer\">true</option>\n" +
"<option name=\"cover_sheet\">false</option>\n" +
"<option name=\"header\">Example Examination Paper</option>\n" +
"<option name=\"question_metrics_qr\">false</option>\n" +
"<option name=\"id_in_footer\">true</option>\n" +
"</options>\n" +
"\n" +
"\n" +
"<questestinterop xmlns=\"http://www.imsglobal.org/xsd/ims_qtiasiv1p2\" xmlns:qyouti=\"http://www.qyouti.org/qtiext\">\n" +
"  <assessment ident=\"assessmentident\" title=\"imported\">\n" +
"    <section ident=\"section1\" title=\"Section 1\">\n" +
"      <outcomes_processing scoremodel=\"SumOfScores\">\n" +
"        <outcomes>\n" +
"          <decvar varname=\"SCORE\" vartype=\"decimal\"/>\n" +
"        </outcomes>\n" +
"      </outcomes_processing>\n" +
"    </section>\n" +
"\n" +
"  </assessment>\n" +
"</questestinterop>\n" +
"\n" +
"<pages>\n" +
"</pages>\n" +
"\n" +
"<candidates>\n" +
"</candidates>\n" +
"\n" +
"<analysis>\n" +
"</analysis>\n" +
"\n" +
"<transforms>\n" +
"</transforms>\n" +
"\n" +
"</examination>";
  


  /**
   * Creates new form EmptyExam
   */
  public EmptyExam()
  {
    initComponents();
  }

  @Override
  public String getDocumentAsString()
  {
    Random r = new Random();
    r.setSeed( System.currentTimeMillis() );
    return text.replaceFirst( "assessmentident", Long.toHexString( r.nextLong() ) );
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();

    setLayout(new java.awt.BorderLayout());

    jLabel1.setText("Empty Exam - no options.");
    add(jLabel1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
