/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti.templates;

import java.awt.*;
import java.util.*;
import java.util.List;
import javax.swing.*;
import org.qyouti.qti1.element.*;

/**
 *
 * @author jon
 */
public class FourOptionMCQNoText
        extends javax.swing.JPanel
        implements ItemTemplate
{
  boolean presentationeditenabled=false;
  boolean processingeditenabled=false;
  QTIElementItem item = null;
  boolean changed=false;

  String itemtitle;  // Title as it was when dialog was opened
  int itemoption;    // Option as it was...
  
  /**
   * Creates new form FourOptionMCQNoText
   */
  public FourOptionMCQNoText()
  {
    initComponents();
    buttongroup.add( buttona );
    buttongroup.add( buttonb );
    buttongroup.add( buttonc );
    buttongroup.add( buttond );
  }

  @Override
  public Component getComponent()
  {
    return this;
  }

  @Override
  public void store()
  {
    String correctident=null;
    
    item.setTitle( titlefield.getText() );
    
    int currentoption = -1;
    if ( buttona.isSelected() )
      currentoption = 0;
    if ( buttonb.isSelected() )
      currentoption = 1;
    if ( buttonc.isSelected() )
      currentoption = 2;
    if ( buttond.isSelected() )
      currentoption = 3;
    
    List<QTIElementResponselabel> l = item.getResponselabels();
    for ( int i=0; i<l.size(); i++ )
    {
      if ( i==currentoption )
      {
        correctident = l.get( i ).getIdent();
        l.get( i ).setCorrect( true );
        l.get( i ).setIncorrect( false );
      }
      else
      {
        l.get( i ).setCorrect( false );
        l.get( i ).setIncorrect( true );
      }
    }
    
    List<QTIElementVarequal> varequals =  item.findElements( QTIElementVarequal.class, true );
    if ( varequals.size() != 1 )
      return;
    QTIElementVarequal v = varequals.get( 0 );
    v.setTextContent( correctident );
  }

  
  public boolean isPresentationeditenabled()
  {
    return presentationeditenabled;
  }

  public void setPresentationeditenabled( boolean presentationeditenabled )
  {
    this.presentationeditenabled = presentationeditenabled;
    titlefield.setEnabled( presentationeditenabled );
  }

  public boolean isProcessingeditenabled()
  {
    return processingeditenabled;
  }

  public void setProcessingeditenabled( boolean processingeditenabled )
  {
    this.processingeditenabled = processingeditenabled;
    buttona.setEnabled( processingeditenabled );
    buttonb.setEnabled( processingeditenabled );
    buttonc.setEnabled( processingeditenabled );
    buttond.setEnabled( processingeditenabled );
  }

  public QTIElementItem getItem()
  {
    return item;
  }

  public void setItem( QTIElementItem item )
  {
    this.item = item;
    this.changed = false;
    itemtitle = item.getTitle();
    List<QTIElementResponselabel> l = item.getResponselabels();
    itemoption = -1;
    for ( int i=0; i<l.size(); i++ )
    {
      if ( l.get( i ).isCorrect() )
      {
        itemoption = i;
        break;
      }
    }
    titlefield.setText( itemtitle );
    JRadioButton[] buttons = {buttona, buttonb, buttonc, buttond};
    if ( itemoption >=0 && itemoption < 4 )
      buttons[itemoption].setSelected( true );
  }  

  @Override
  public boolean isChanged()
  {
    evaluateChange();
    return changed;
  }

  void evaluateChange()
  {
    int currentoption = -1;
    if ( buttona.isSelected() )
      currentoption = 0;
    if ( buttonb.isSelected() )
      currentoption = 1;
    if ( buttonc.isSelected() )
      currentoption = 2;
    if ( buttond.isSelected() )
      currentoption = 3;
    String currenttitle = titlefield.getText();
    changed =  currentoption != itemoption || !currenttitle.equals( itemtitle );
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    buttongroup = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    titlelabel = new javax.swing.JLabel();
    titlefield = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    correctlabel = new javax.swing.JLabel();
    buttona = new javax.swing.JRadioButton();
    buttonb = new javax.swing.JRadioButton();
    buttonc = new javax.swing.JRadioButton();
    buttond = new javax.swing.JRadioButton();

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Presentation"));

    titlelabel.setText("Title:");
    jPanel1.add(titlelabel);

    titlefield.setColumns(30);
    titlefield.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        titlefieldActionPerformed(evt);
      }
    });
    jPanel1.add(titlefield);

    add(jPanel1);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Response Processing"));

    correctlabel.setText("Correct Answer:");
    jPanel2.add(correctlabel);

    buttona.setText("A");
    buttona.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        buttonaActionPerformed(evt);
      }
    });
    jPanel2.add(buttona);

    buttonb.setText("B");
    buttonb.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        buttonbActionPerformed(evt);
      }
    });
    jPanel2.add(buttonb);

    buttonc.setText("C");
    buttonc.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        buttoncActionPerformed(evt);
      }
    });
    jPanel2.add(buttonc);

    buttond.setText("D");
    buttond.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        buttondActionPerformed(evt);
      }
    });
    jPanel2.add(buttond);

    add(jPanel2);
  }// </editor-fold>//GEN-END:initComponents

  private void buttonbActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonbActionPerformed
  {//GEN-HEADEREND:event_buttonbActionPerformed
    
  }//GEN-LAST:event_buttonbActionPerformed

  private void titlefieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_titlefieldActionPerformed
  {//GEN-HEADEREND:event_titlefieldActionPerformed
    
    // TODO add your handling code here:
  }//GEN-LAST:event_titlefieldActionPerformed

  private void buttonaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonaActionPerformed
  {//GEN-HEADEREND:event_buttonaActionPerformed

    // TODO add your handling code here:
  }//GEN-LAST:event_buttonaActionPerformed

  private void buttoncActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttoncActionPerformed
  {//GEN-HEADEREND:event_buttoncActionPerformed

    // TODO add your handling code here:
  }//GEN-LAST:event_buttoncActionPerformed

  private void buttondActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttondActionPerformed
  {//GEN-HEADEREND:event_buttondActionPerformed

    // TODO add your handling code here:
  }//GEN-LAST:event_buttondActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButton buttona;
  private javax.swing.JRadioButton buttonb;
  private javax.swing.JRadioButton buttonc;
  private javax.swing.JRadioButton buttond;
  private javax.swing.ButtonGroup buttongroup;
  private javax.swing.JLabel correctlabel;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTextField titlefield;
  private javax.swing.JLabel titlelabel;
  // End of variables declaration//GEN-END:variables
}
