/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti.templates;

import java.awt.*;
import net.atlanticbb.tantlinger.shef.*;
import org.qyouti.qti1.element.*;

/**
 *
 * @author jon
 */
public class MattextPanel
        extends javax.swing.JPanel
{
  QTIElementMattext mattext;
  String initialcontent;
  boolean changed=false;
  
  /**
   * Creates new form MattextPanel
   */
  public MattextPanel( QTIElementMattext mattext )
  {
    this.mattext = mattext;
    initComponents();
    initialcontent = mattext.getContent();
    //htmleditorpane.setComplexToolbar( false );
    htmleditorpane.setText( initialcontent );
  }
  
  @Override
  public void setEnabled( boolean enabled )
  {
    super.setEnabled( enabled );
    htmleditorpane.setEnabled( enabled );
  }
  
  public boolean isChanged()
  {
    evaluateChange();
    return changed;
  }

  void evaluateChange()
  {
    String str = htmleditorpane.getText();
    changed =  str != initialcontent;
  }

  void store()
  {
    String str = htmleditorpane.getText();
    int n = str.indexOf( "<body" );
    if ( n>=0 )
    {
      str = str.substring( n );
      n = str.indexOf( ">" );
      str = str.substring( n+1 );
      n = str.indexOf( "</body>" );
      if ( n>=0 )
        str = str.substring( 0, n );
    }
    mattext.setContent( str );
    initialcontent = str;
  }
  
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    htmleditorpane = new net.atlanticbb.tantlinger.shef.HTMLEditorPane();

    setLayout(new java.awt.CardLayout());
    add(htmleditorpane, "card2");
  }// </editor-fold>//GEN-END:initComponents

  private void editorpaneFocusLost(java.awt.event.FocusEvent evt)                                             
  {                                                 
    System.out.println( "HTML Editor lost focus." );
    CardLayout l = (CardLayout)this.getLayout();
    l.show( this, "preview" );
  }                                        
  
  

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private net.atlanticbb.tantlinger.shef.HTMLEditorPane htmleditorpane;
  // End of variables declaration//GEN-END:variables
}
