/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

import java.awt.*;
import java.awt.event.*;
import java.awt.image.*;
import java.io.*;
import javax.imageio.*;
import javax.swing.*;
import javax.swing.event.*;
import org.qyouti.data.*;
import org.qyouti.qti1.element.*;

/**
 *
 * @author jon
 */
public class CandidateQuestionPanel
        extends javax.swing.JPanel
{
  CandidateData candidate;
  String questionident;
  QuestionData questiondata;
  QTIElementItem item;
  
  BufferedImage questionimage;
  
  /**
   * Creates new form CandidateQuestionPanel
   */
  public CandidateQuestionPanel( CandidateData cd, String ident )
  {
    candidate = cd;
    questionident = ident;
    item = candidate.exam.qdefs.qti.getItem( ident );
    questiondata = candidate.getQuestionData( ident );
    
    initComponents();
    
    if ( item == null )
    {
      titlelabel.setText( "Missing Question: " + ident );
      return;
    }
    
    if ( item.getTitle() == null || item.getTitle().length() == 0 )
      titlelabel.setText("Untitled Question" );
    else
      titlelabel.setText( item.getTitle() );
    
    if ( questiondata == null )
    {
      statuslabel.setText( "Not scanned" );
      centrepanel.setVisible( false );
    }
    else
    {
      if ( questiondata.needsreview )
      {
        switch ( questiondata.getExaminerDecision() )
        {
          case QuestionData.EXAMINER_DECISION_NONE:
            statuslabel.setText( "Review recommended." );
            break;
          case QuestionData.EXAMINER_DECISION_OVERRIDE:
            statuslabel.setText( "Responses overridden by examiner. (Review was recommended.)" );
            break;
          case QuestionData.EXAMINER_DECISION_STAND:
            statuslabel.setText( "Examiner decided responses will stand. (Review was recommended.)" );
            break;            
        }
      }
      else
      {
        switch ( questiondata.getExaminerDecision() )
        {
          case QuestionData.EXAMINER_DECISION_NONE:
            statuslabel.setText( "Review not recommended." );
            break;
          case QuestionData.EXAMINER_DECISION_OVERRIDE:
            statuslabel.setText( "Responses overridden by examiner. (Review was not recommended.)" );
            break;
          case QuestionData.EXAMINER_DECISION_STAND:
            statuslabel.setText( "Examiner decided responses will stand.  (Review was not recommended.)" );
            break;            
        }
      }

      switch ( questiondata.getExaminerDecision() )
      {
        case QuestionData.EXAMINER_DECISION_NONE:
          reviewcombobox.setSelectedIndex( 0 );
          break;
        case QuestionData.EXAMINER_DECISION_STAND:
          reviewcombobox.setSelectedIndex( 1 );
          break;            
        case QuestionData.EXAMINER_DECISION_OVERRIDE:
          reviewcombobox.setSelectedIndex( 2 );
          break;
      }

      responsetable.setModel( questiondata );
      questiondata.addTableModelListener( new TableModelListener(){
        @Override
        public void tableChanged( TableModelEvent e )
        {
          System.out.println( "CandidateQuestionPanel detected table change." );
          for ( int i=0; i<questiondata.getRowCount(); i++ )
            responsetable.setRowHeight( i, questiondata.getRowHeight( i ) );
          // Unable to set row height here...
          // Maybe better not to add/remove columns but just change
          // content of the last column
          
        }
      } );
      for ( int i=0; i<questiondata.getRowCount(); i++ )
        responsetable.setRowHeight( i, questiondata.getRowHeight( i ) );
      //responsetable.getColumnModel().getColumn( 4 ).setCellRenderer( new PinkBoxTableCellRenderer() );
      DefaultCellEditor dce;
      JCheckBox cb = new JCheckBox();
      cb.setSelectedIcon( TrueFalseIcon.TRUEICON );
      cb.setIcon( TrueFalseIcon.FALSEICON );
      dce = new DefaultCellEditor( cb );
      responsetable.setDefaultEditor( Boolean.class, dce);
      responsetable.setDefaultRenderer( Boolean.class, new PinkBoxTableCellRenderer() );
      outcometable.setModel( questiondata.outcomes );
    }
    
    imagescrollpanel.setVisible( true );
    responsetablepanel.setVisible( true );
    loadQuestionImage();
    responsetablepanel.add( responsetable.getTableHeader(), java.awt.BorderLayout.NORTH );
    responsetable.setMinimumSize(new Dimension(200,responsetable.getRowHeight( 0 )*responsetable.getRowCount()));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    toppanel = new javax.swing.JPanel();
    titlelabel = new javax.swing.JLabel();
    statuslabel = new javax.swing.JLabel();
    centrepanel = new javax.swing.JPanel();
    innerpanel = new javax.swing.JPanel();
    reviewcombobox = new javax.swing.JComboBox<>();
    outcomepanel = new javax.swing.JPanel();
    outcometable = new javax.swing.JTable();
    imagepanel = new javax.swing.JPanel();
    viewimagecheckbox = new javax.swing.JCheckBox();
    imagescrollpanel = new javax.swing.JScrollPane();
    imagelabel = new javax.swing.JLabel();
    responsepanel = new javax.swing.JPanel();
    viewresponsescheckbox = new javax.swing.JCheckBox();
    responsetablepanel = new javax.swing.JPanel();
    responsetable = new javax.swing.JTable();
    jSeparator1 = new javax.swing.JSeparator();

    setBackground(java.awt.Color.white);
    setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 12, 12, 12));
    setLayout(new java.awt.BorderLayout());

    toppanel.setBackground(java.awt.Color.white);
    toppanel.setLayout(new java.awt.GridLayout(0, 1));

    titlelabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    titlelabel.setText("Title of Question");
    toppanel.add(titlelabel);

    statuslabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    statuslabel.setText("question status");
    toppanel.add(statuslabel);

    add(toppanel, java.awt.BorderLayout.NORTH);

    centrepanel.setBackground(java.awt.Color.white);
    centrepanel.setLayout(new java.awt.GridBagLayout());

    innerpanel.setBackground(java.awt.Color.white);
    innerpanel.setLayout(new java.awt.GridBagLayout());

    reviewcombobox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    reviewcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Reviewed", "Confirm", "Override" }));
    reviewcombobox.addItemListener(new java.awt.event.ItemListener()
    {
      public void itemStateChanged(java.awt.event.ItemEvent evt)
      {
        reviewcomboboxItemStateChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    innerpanel.add(reviewcombobox, gridBagConstraints);

    outcomepanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Question Outcomes"));
    outcomepanel.setOpaque(false);
    outcomepanel.setLayout(new java.awt.GridBagLayout());

    outcometable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null}
      },
      new String []
      {
        "Title 1", "Title 2"
      }
    ));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    outcomepanel.add(outcometable, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    innerpanel.add(outcomepanel, gridBagConstraints);

    imagepanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Scanned Image"));
    imagepanel.setOpaque(false);
    imagepanel.setLayout(new java.awt.BorderLayout());

    viewimagecheckbox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    viewimagecheckbox.setSelected(true);
    viewimagecheckbox.setText("Show");
    viewimagecheckbox.setOpaque(false);
    viewimagecheckbox.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        viewimagecheckboxActionPerformed(evt);
      }
    });
    imagepanel.add(viewimagecheckbox, java.awt.BorderLayout.NORTH);

    imagescrollpanel.setBackground(java.awt.Color.white);
    imagescrollpanel.setBorder(null);
    imagescrollpanel.setOpaque(false);

    imagelabel.setBackground(java.awt.Color.white);
    imagelabel.setText("      ");
    imagelabel.setOpaque(true);
    imagescrollpanel.setViewportView(imagelabel);

    imagepanel.add(imagescrollpanel, java.awt.BorderLayout.CENTER);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    innerpanel.add(imagepanel, gridBagConstraints);

    responsepanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Responses"));
    responsepanel.setOpaque(false);
    responsepanel.setLayout(new java.awt.BorderLayout());

    viewresponsescheckbox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    viewresponsescheckbox.setSelected(true);
    viewresponsescheckbox.setText("Show");
    viewresponsescheckbox.setOpaque(false);
    viewresponsescheckbox.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        viewresponsescheckboxActionPerformed(evt);
      }
    });
    responsepanel.add(viewresponsescheckbox, java.awt.BorderLayout.NORTH);

    responsetablepanel.setLayout(new java.awt.BorderLayout());

    responsetable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {

      },
      new String []
      {
        "A", "B", "C", "D"
      }
    )
    {
      boolean[] canEdit = new boolean []
      {
        false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex)
      {
        return canEdit [columnIndex];
      }
    });
    responsetable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
    responsetablepanel.add(responsetable, java.awt.BorderLayout.CENTER);

    responsepanel.add(responsetablepanel, java.awt.BorderLayout.CENTER);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    innerpanel.add(responsepanel, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(12, 0, 12, 0);
    innerpanel.add(jSeparator1, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.weighty = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    centrepanel.add(innerpanel, gridBagConstraints);

    add(centrepanel, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void loadQuestionImage()
  {
    try
    {
      if ( questiondata == null || !questiondata.getImageFile().exists() )
      {
        imagelabel.setText( "Not Scanned" );
      }
      else
      {
        questionimage = ImageIO.read( questiondata.getImageFile() );
        imagelabel.setIcon( new ImageIcon( questionimage ) );        
        imagelabel.setText( "" );
      }
    }
    catch ( IOException ioe )
    {
      imagelabel.setText( "Unable to Load" );
    }    
  }
  
  private void viewimagecheckboxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_viewimagecheckboxActionPerformed
  {//GEN-HEADEREND:event_viewimagecheckboxActionPerformed
    
    imagelabel.setIcon( null );
    imagelabel.setText( "" );
      
    if ( !viewimagecheckbox.isSelected() )
    {
      questionimage = null;
      imagescrollpanel.setVisible( false );
      revalidate();
      return;
    }

    loadQuestionImage();

    imagescrollpanel.setVisible( true );
    revalidate();    
  }//GEN-LAST:event_viewimagecheckboxActionPerformed

  private void viewresponsescheckboxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_viewresponsescheckboxActionPerformed
  {//GEN-HEADEREND:event_viewresponsescheckboxActionPerformed
      responsetablepanel.setVisible( viewresponsescheckbox.isSelected() );
      revalidate();
  }//GEN-LAST:event_viewresponsescheckboxActionPerformed

  private void reviewcomboboxItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_reviewcomboboxItemStateChanged
  {//GEN-HEADEREND:event_reviewcomboboxItemStateChanged

    if ( evt.getStateChange() == ItemEvent.SELECTED )
    {
      int n = reviewcombobox.getSelectedIndex();
      if ( n != questiondata.getExaminerDecision() )
      {
        System.out.println( "examiner decision combo box change." );
        questiondata.setExaminerDecision( n );
        candidate.exam.setUnsavedChanges( true );
      }
    }
  }//GEN-LAST:event_reviewcomboboxItemStateChanged


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel centrepanel;
  private javax.swing.JLabel imagelabel;
  private javax.swing.JPanel imagepanel;
  private javax.swing.JScrollPane imagescrollpanel;
  private javax.swing.JPanel innerpanel;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JPanel outcomepanel;
  private javax.swing.JTable outcometable;
  private javax.swing.JPanel responsepanel;
  private javax.swing.JTable responsetable;
  private javax.swing.JPanel responsetablepanel;
  private javax.swing.JComboBox<String> reviewcombobox;
  private javax.swing.JLabel statuslabel;
  private javax.swing.JLabel titlelabel;
  private javax.swing.JPanel toppanel;
  private javax.swing.JCheckBox viewimagecheckbox;
  private javax.swing.JCheckBox viewresponsescheckbox;
  // End of variables declaration//GEN-END:variables
}
