/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.quipto.compositefile.EncryptedCompositeFileUser;
import org.qyouti.crypto.CryptographyManager;
import org.qyouti.crypto.CryptographyManagerException;

/**
 *
 * @author maber01
 */
public class CreateIdentityDialog
        extends javax.swing.JDialog
{
  CryptographyManager cryptoman;
  EncryptedCompositeFileUser user;
  
  /**
   * Creates new form IdentityDialog
   */
  public CreateIdentityDialog(java.awt.Frame parent, CryptographyManager cryptoman )
  {
    super(parent, true);
    this.cryptoman = cryptoman;
    initComponents();

  }


  
  public boolean validateInput()
  {
    String name = nametextfield.getText().trim();
    String email = emailtextfield.getText().trim();
    
    if ( name.length() < 2 )
    {
      JOptionPane.showMessageDialog( rootPane, "Name too short." );
      return false;
    }
    if ( email.length() < 3 )
    {
      JOptionPane.showMessageDialog( rootPane, "Email address too short." );
      return false;
    }
    if ( !email.contains("@") )
    {
      JOptionPane.showMessageDialog( rootPane, "Email address lacks @." );
      return false;
    }
   
    return true;
  }
  
  
  public boolean createKeyPair()
  {
    String name     = nametextfield.getText().trim();
    String username = usernametextfield.getText().trim();
    String email    = emailtextfield.getText().trim();

    String alias = name + " (" + username + ") <" + email + ">";

    try
    {
      cryptoman.createNewKeys(alias, null, true);
    }
    catch (CryptographyManagerException ex)
    {
      JOptionPane.showMessageDialog(rootPane, ex.getMessage() );
      return false;
    }

    return true;
  }
  
  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel2 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    nametextfield = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    usernametextfield = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    emailtextfield = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    createnewkeysbutton = new javax.swing.JButton();
    closebutton = new javax.swing.JButton();

    jLabel2.setText("jLabel2");

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel3.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Name:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel3.add(jLabel1, gridBagConstraints);

    nametextfield.setMinimumSize(new java.awt.Dimension(200, 28));
    nametextfield.setPreferredSize(new java.awt.Dimension(200, 28));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel3.add(nametextfield, gridBagConstraints);

    jLabel6.setText("Computer User Name:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel3.add(jLabel6, gridBagConstraints);

    usernametextfield.setMinimumSize(new java.awt.Dimension(200, 28));
    usernametextfield.setPreferredSize(new java.awt.Dimension(200, 28));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel3.add(usernametextfield, gridBagConstraints);

    jLabel3.setText("Email Address:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel3.add(jLabel3, gridBagConstraints);

    emailtextfield.setMinimumSize(new java.awt.Dimension(200, 28));
    emailtextfield.setPreferredSize(new java.awt.Dimension(200, 28));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    jPanel3.add(emailtextfield, gridBagConstraints);

    getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

    createnewkeysbutton.setText("Create");
    createnewkeysbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        createnewkeysbuttonActionPerformed(evt);
      }
    });
    jPanel2.add(createnewkeysbutton);

    closebutton.setText("Cancel");
    closebutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        closebuttonActionPerformed(evt);
      }
    });
    jPanel2.add(closebutton);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void createnewkeysbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_createnewkeysbuttonActionPerformed
  {//GEN-HEADEREND:event_createnewkeysbuttonActionPerformed
    
    if ( !validateInput() )
      return;
    
    if ( !createKeyPair() )
      return;
    
    dispose();
  }//GEN-LAST:event_createnewkeysbuttonActionPerformed

  private void closebuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closebuttonActionPerformed
  {//GEN-HEADEREND:event_closebuttonActionPerformed
    dispose();
  }//GEN-LAST:event_closebuttonActionPerformed



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton closebutton;
  private javax.swing.JButton createnewkeysbutton;
  private javax.swing.JTextField emailtextfield;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JTextField nametextfield;
  private javax.swing.JTextField usernametextfield;
  // End of variables declaration//GEN-END:variables
}
