/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

import java.util.Arrays;
import javax.swing.JOptionPane;
import org.qyouti.crypto.CryptographyManager;

/**
 *
 * @author maber01
 */
public class CreatePersonalKeystoreDialog
        extends javax.swing.JDialog
{
  public static final int OPTION_EXIT = 0;
  public static final int OPTION_CREATE = 1;

  int option = OPTION_EXIT;
  
  boolean winavailable;
  boolean usewin;
  char[] pass;
  
  /**
   * Creates new form CreatePersonalKeystoreDialog
   */
  public CreatePersonalKeystoreDialog( java.awt.Frame parent, boolean modal, CryptographyManager cryptoman )
  {
    super(parent, modal);
    initComponents();
    winavailable = cryptoman.isWindowsAvailable();
    if ( winavailable )
    {
      windowscheckbox.setEnabled( true );
      windowscheckbox.setSelected( true );
    }
    else
    {
      windowscheckbox.setEnabled( false );
      windowscheckbox.setSelected( false );      
    }
  }

  public void updateFields()
  {
    if ( windowscheckbox.isSelected() )
    {
      passchoose.setText("");
      passconfirm.setText("");
      passchoose.setEnabled( false );
      passconfirm.setEnabled( false );
    }
    else
    {
      passchoose.setEnabled( true );
      passconfirm.setEnabled( true );      
    }
  }
  
  public int getOption()
  {
    return option;
  }
  
  public boolean useWindows()
  {
    return usewin;
  }
  
  public char[] getPass()
  {
    return pass;
  }
  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jPanel1 = new javax.swing.JPanel();
    jTextArea1 = new javax.swing.JTextArea();
    windowscheckbox = new javax.swing.JCheckBox();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    passchoose = new javax.swing.JPasswordField();
    passconfirm = new javax.swing.JPasswordField();
    jPanel2 = new javax.swing.JPanel();
    createbutton = new javax.swing.JButton();
    exitbutton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jTextArea1.setColumns(20);
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setText("You don't yet have a personal key store. This is needed in order to gain access to examination data.");
    jTextArea1.setWrapStyleWord(true);
    jTextArea1.setOpaque(false);

    windowscheckbox.setSelected(true);
    windowscheckbox.setText("Protect key store with Windows cryptographic services");
    windowscheckbox.setEnabled(false);
    windowscheckbox.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        windowscheckboxActionPerformed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText("Choose Password:");

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel2.setText("Confirm Password:");

    passchoose.setEnabled(false);

    passconfirm.setEnabled(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jTextArea1)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(windowscheckbox)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(passchoose)
              .addComponent(passconfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(windowscheckbox)
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(passchoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(passconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(41, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    createbutton.setText("Create");
    createbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        createbuttonActionPerformed(evt);
      }
    });
    jPanel2.add(createbutton);

    exitbutton.setText("Exit");
    exitbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        exitbuttonActionPerformed(evt);
      }
    });
    jPanel2.add(exitbutton);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void windowscheckboxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_windowscheckboxActionPerformed
  {//GEN-HEADEREND:event_windowscheckboxActionPerformed
    
    updateFields();
    
  }//GEN-LAST:event_windowscheckboxActionPerformed

  private void createbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_createbuttonActionPerformed
  {//GEN-HEADEREND:event_createbuttonActionPerformed
    usewin = windowscheckbox.isSelected();
    
    if ( usewin )
    {
      pass = null;
    }
    else
    {
      char[] pwa = passchoose.getPassword();
      char[] pwb = passconfirm.getPassword();
      if ( !Arrays.equals( pwa, pwb ) )
      {
        JOptionPane.showMessageDialog(rootPane, "The content of the two password boxes do not match.");
        return;
      }
      if ( pwa.length < 10 )
      {
        JOptionPane.showMessageDialog(rootPane, "The password has to be at least ten character long.");
        return;
      }
      pass = pwa;
    }
    option = OPTION_CREATE;
    dispose();    
  }//GEN-LAST:event_createbuttonActionPerformed

  private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitbuttonActionPerformed
  {//GEN-HEADEREND:event_exitbuttonActionPerformed
    option = OPTION_EXIT;
    dispose();    
  }//GEN-LAST:event_exitbuttonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton createbutton;
  private javax.swing.JButton exitbutton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JPasswordField passchoose;
  private javax.swing.JPasswordField passconfirm;
  private javax.swing.JCheckBox windowscheckbox;
  // End of variables declaration//GEN-END:variables
}
