/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

import java.io.*;
import java.util.*;
import javax.swing.*;
import org.qyouti.data.*;

/**
 *
 * @author jon
 */
public class ExamSelectDialog
        extends javax.swing.JDialog
{

  QyoutiFrame frame;
  File basefolder;
  ExaminationCatalogue examcatalogue;
  DefaultListModel<String> listmodel;
  int type;
  
  /**
   * Creates new form NewExamDialog
   */
  public ExamSelectDialog( java.awt.Frame parent, boolean modal )
  {
    super( parent, modal );
    initComponents();
    listmodel = new DefaultListModel<String>();
    examlist.setModel( listmodel );
  }

  public static final int TYPE_NEW = 1;
  public static final int TYPE_OPEN = 2;
  
  public void setDialogType( int type )
  {
    this.type = type;
    
    if ( type != TYPE_NEW && type != TYPE_OPEN )
      throw new IllegalArgumentException( "Unkown type of dialog box requested." );
    openbutton.setText( type==TYPE_NEW?"Create":"Open" );
    namefield.setEditable( type==TYPE_NEW );
    setTitle( type==TYPE_NEW?"Create New Exam/Survey":"Open Exam/Survey" );
    examlist.setEnabled( type==TYPE_OPEN );
  }

  public int getDialogType()
  {
    return type;
  }

  
  public File getBaseFolder()
  {
    return basefolder;
  }

  public void setBaseFolder( File basefolder )
  {
    this.basefolder = basefolder;
    examcatalogue = new ExaminationCatalogue( basefolder );
    baselabel.setText( basefolder.getAbsolutePath() );
    updateList();
  }

  public ExaminationCatalogue getExaminationCatalogue()
  {
    return this.examcatalogue;
  }
  
  public String getExamName()
  {
    return namefield.getText();
  }

  public void setExamName( String name )
  {
    this.namefield.setText( name );
  }

  public void setFrame( QyoutiFrame frame )
  {
    this.frame = frame;
  }
  
  public void updateList()
  {
    String[] list = examcatalogue.getNames();
    listmodel.clear();
    for ( int i=0; i<list.length; i++ )
      listmodel.addElement( list[i] );
    

//    File folder = new File( getBaseFolder() );
//    File[] children = folder.listFiles();
//    Arrays.sort( children, new Comparator<File>(){
//      @Override
//      public int compare( File o1, File o2 )
//      {
//        return o1.getName().compareTo( o2.getName() );
//      }
//    } );
//    File qyoutifile;
//    for ( int i=0; i<children.length; i++ )
//    {
//      if ( !children[i].isDirectory() )
//        continue;
//      qyoutifile = new File( children[i], "qyouti.xml" );
//      if ( qyoutifile.isFile() )
//        listmodel.addElement( children[i].getName() );
//    } 
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    jTextField1 = new javax.swing.JTextField();
    rootpanel = new javax.swing.JPanel();
    toppanel = new javax.swing.JPanel();
    l1 = new javax.swing.JLabel();
    baselabel = new javax.swing.JLabel();
    changebutton = new javax.swing.JButton();
    centrepanel = new javax.swing.JPanel();
    sp1 = new javax.swing.JScrollPane();
    examlist = new javax.swing.JList<>();
    bottompanel = new javax.swing.JPanel();
    l2 = new javax.swing.JLabel();
    namefield = new javax.swing.JTextField();
    openbutton = new javax.swing.JButton();
    cancelbutton = new javax.swing.JButton();

    jTextField1.setText("jTextField1");

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("New/Open Exam/Survey");
    setModal(true);
    getContentPane().setLayout(new java.awt.BorderLayout(8, 8));

    rootpanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    rootpanel.setLayout(new java.awt.BorderLayout());

    toppanel.setLayout(new java.awt.BorderLayout(10, 0));

    l1.setText("Base Folder:");
    toppanel.add(l1, java.awt.BorderLayout.WEST);
    toppanel.add(baselabel, java.awt.BorderLayout.CENTER);

    changebutton.setText("Change...");
    changebutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        changebuttonActionPerformed(evt);
      }
    });
    toppanel.add(changebutton, java.awt.BorderLayout.EAST);

    rootpanel.add(toppanel, java.awt.BorderLayout.NORTH);

    centrepanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20), javax.swing.BorderFactory.createTitledBorder("Exams/Surveys")));
    centrepanel.setLayout(new java.awt.BorderLayout());

    examlist.addListSelectionListener(new javax.swing.event.ListSelectionListener()
    {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt)
      {
        handleListChange(evt);
      }
    });
    sp1.setViewportView(examlist);

    centrepanel.add(sp1, java.awt.BorderLayout.CENTER);

    rootpanel.add(centrepanel, java.awt.BorderLayout.CENTER);

    bottompanel.setLayout(new java.awt.GridBagLayout());

    l2.setText("Exam/Survey Name:");
    bottompanel.add(l2, new java.awt.GridBagConstraints());

    namefield.setColumns(20);
    bottompanel.add(namefield, new java.awt.GridBagConstraints());

    openbutton.setText("Open");
    openbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        openbuttonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    bottompanel.add(openbutton, gridBagConstraints);

    cancelbutton.setText("Cancel");
    cancelbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelbuttonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    bottompanel.add(cancelbutton, gridBagConstraints);

    rootpanel.add(bottompanel, java.awt.BorderLayout.SOUTH);

    getContentPane().add(rootpanel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void openbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_openbuttonActionPerformed
  {//GEN-HEADEREND:event_openbuttonActionPerformed
    if ( frame == null )
      dispose();
    
    if ( frame.examSelectDialogDone() )
      dispose();
  }//GEN-LAST:event_openbuttonActionPerformed

  private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelbuttonActionPerformed
  {//GEN-HEADEREND:event_cancelbuttonActionPerformed
    dispose();
  }//GEN-LAST:event_cancelbuttonActionPerformed

  private void changebuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_changebuttonActionPerformed
  {//GEN-HEADEREND:event_changebuttonActionPerformed
    JFileChooser fc = new JFileChooser();
    fc.setDialogTitle( "Select folder containing exams and surveys." );
    fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);    
    int returnVal = fc.showOpenDialog(this);
    File folder;
    if (returnVal != JFileChooser.APPROVE_OPTION)
      return;
    
    folder = fc.getSelectedFile();
    setBaseFolder( folder );
  }//GEN-LAST:event_changebuttonActionPerformed

  private void handleListChange(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_handleListChange
  {//GEN-HEADEREND:event_handleListChange
    if ( evt.getValueIsAdjusting() ) return;
    System.out.println( "list change " + examlist.getSelectedValue() );
    namefield.setText( examlist.getSelectedValue() );
  }//GEN-LAST:event_handleListChange


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel baselabel;
  private javax.swing.JPanel bottompanel;
  private javax.swing.JButton cancelbutton;
  private javax.swing.JPanel centrepanel;
  private javax.swing.JButton changebutton;
  private javax.swing.JList<String> examlist;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JLabel l1;
  private javax.swing.JLabel l2;
  private javax.swing.JTextField namefield;
  private javax.swing.JButton openbutton;
  private javax.swing.JPanel rootpanel;
  private javax.swing.JScrollPane sp1;
  private javax.swing.JPanel toppanel;
  // End of variables declaration//GEN-END:variables
}
