/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

import java.util.*;
import org.qyouti.data.*;

/**
 *
 * @author jon
 */
public class ExamPropertiesDialog
        extends javax.swing.JDialog
{
  QyoutiFrame parent;
  ExaminationData exam;
  
  /**
   * Creates new form ExamPropertiesDialog
   */
  public ExamPropertiesDialog( QyoutiFrame parent, boolean modal )
  {
    super( parent, modal );
    this.parent = parent;
    initComponents();
  }

  public void setExaminationData( ExaminationData exam )
  {
    this.exam = exam;
    headerfield.setText( exam.getQTIRenderOption( "header" ) );
    nameinfootercheckbox.setSelected( exam.getQTIRenderBooleanOption( "name_in_footer" ) );
    idinfootercheckbox.setSelected( exam.getQTIRenderBooleanOption( "id_in_footer" ) );
    printtitlescheckbox.setSelected( exam.getQTIRenderBooleanOption( "question_titles" ) );
    doublesidedcheckbox.setSelected( exam.getQTIRenderBooleanOption( "double_sided" ) );
    coversheetcheckbox.setSelected( exam.getQTIRenderBooleanOption( "cover_sheet" ) );
    int layout = exam.getQTIRenderIntegerOption("layout");
    switch ( layout )
    {
      case 2:
        layoutbuttongroup.setSelected(layout2button.getModel(), true);
        break;
      default:
        layoutbuttongroup.setSelected(layout1button.getModel(), true);
    }
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    layoutbuttongroup = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    headerlabel = new javax.swing.JLabel();
    headerfield = new javax.swing.JTextField();
    nameinfootercheckbox = new javax.swing.JCheckBox();
    idinfootercheckbox = new javax.swing.JCheckBox();
    printtitlescheckbox = new javax.swing.JCheckBox();
    doublesidedcheckbox = new javax.swing.JCheckBox();
    coversheetcheckbox = new javax.swing.JCheckBox();
    jPanel3 = new javax.swing.JPanel();
    layout1button = new javax.swing.JRadioButton();
    layout2button = new javax.swing.JRadioButton();
    jPanel2 = new javax.swing.JPanel();
    setbutton = new javax.swing.JButton();
    cancelbutton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Exam/Survey Properties");

    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

    headerlabel.setText("Header Text:");
    jPanel1.add(headerlabel);
    jPanel1.add(headerfield);

    nameinfootercheckbox.setText("Name in Footer");
    jPanel1.add(nameinfootercheckbox);

    idinfootercheckbox.setText("ID in Footer");
    idinfootercheckbox.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        idinfootercheckboxActionPerformed(evt);
      }
    });
    jPanel1.add(idinfootercheckbox);

    printtitlescheckbox.setText("Print Question Titles");
    printtitlescheckbox.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        printtitlescheckboxActionPerformed(evt);
      }
    });
    jPanel1.add(printtitlescheckbox);

    doublesidedcheckbox.setText("Double Sided");
    jPanel1.add(doublesidedcheckbox);

    coversheetcheckbox.setText("Add Cover Sheet");
    jPanel1.add(coversheetcheckbox);

    jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

    layoutbuttongroup.add(layout1button);
    layout1button.setSelected(true);
    layout1button.setText("Layout left barcode");
    jPanel3.add(layout1button);

    layoutbuttongroup.add(layout2button);
    layout2button.setText("Layout bottom barcode");
    jPanel3.add(layout2button);

    jPanel1.add(jPanel3);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    setbutton.setText("Set");
    setbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        setbuttonActionPerformed(evt);
      }
    });
    jPanel2.add(setbutton);

    cancelbutton.setText("Cancel");
    cancelbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelbuttonActionPerformed(evt);
      }
    });
    jPanel2.add(cancelbutton);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void printtitlescheckboxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printtitlescheckboxActionPerformed
  {//GEN-HEADEREND:event_printtitlescheckboxActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_printtitlescheckboxActionPerformed

  private void idinfootercheckboxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_idinfootercheckboxActionPerformed
  {//GEN-HEADEREND:event_idinfootercheckboxActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_idinfootercheckboxActionPerformed

  
  
  private void setbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_setbuttonActionPerformed
  {//GEN-HEADEREND:event_setbuttonActionPerformed

    exam.setOption( "header",          headerfield.getText() );
    exam.setOption( "name_in_footer",  nameinfootercheckbox.isSelected() );
    exam.setOption( "id_in_footer",    idinfootercheckbox.isSelected() );
    exam.setOption( "question_titles", printtitlescheckbox.isSelected() );
    exam.setOption( "double_sided",    doublesidedcheckbox.isSelected() );
    exam.setOption( "cover_sheet",     coversheetcheckbox.isSelected() );
    if ( layout2button.isSelected() )
      exam.setOption( "layout", "2" );
    else
      exam.setOption( "layout", "1" );
    parent.examOptionsSaved();
    setVisible( false );
    dispose();
    
  }//GEN-LAST:event_setbuttonActionPerformed

  private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelbuttonActionPerformed
  {//GEN-HEADEREND:event_cancelbuttonActionPerformed

    setVisible( false );
    dispose();
    
  }//GEN-LAST:event_cancelbuttonActionPerformed



  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelbutton;
  private javax.swing.JCheckBox coversheetcheckbox;
  private javax.swing.JCheckBox doublesidedcheckbox;
  private javax.swing.JTextField headerfield;
  private javax.swing.JLabel headerlabel;
  private javax.swing.JCheckBox idinfootercheckbox;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JRadioButton layout1button;
  private javax.swing.JRadioButton layout2button;
  private javax.swing.ButtonGroup layoutbuttongroup;
  private javax.swing.JCheckBox nameinfootercheckbox;
  private javax.swing.JCheckBox printtitlescheckbox;
  private javax.swing.JButton setbutton;
  // End of variables declaration//GEN-END:variables
}
