/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

import java.net.*;
import java.util.logging.*;
import javax.swing.*;

/**
 *
 * @author jon
 */
public class ImageViewDialog
        extends javax.swing.JDialog
{

  /**
   * Creates new form ImageViewDialog
   */
  public ImageViewDialog( java.awt.Frame parent, boolean modal )
  {
    super( parent, modal );
    initComponents();
  }

  public void setImage( String filename )
  {
    try
    {
      URL url = new URL( filename );
      imagelabel.setIcon( new ImageIcon(url) );
      pack();
    }
    catch ( MalformedURLException ex )
    {
      Logger.getLogger( ImageViewDialog.class.getName() ).log( Level.SEVERE, null, ex );
    }
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    scrollpane = new javax.swing.JScrollPane();
    imagelabel = new javax.swing.JLabel();
    bottompanel = new javax.swing.JPanel();
    closebutton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("View Scan Image");

    scrollpane.setViewportView(imagelabel);

    getContentPane().add(scrollpane, java.awt.BorderLayout.CENTER);

    closebutton.setText("Close");
    closebutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        closebuttonActionPerformed(evt);
      }
    });
    bottompanel.add(closebutton);

    getContentPane().add(bottompanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void closebuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closebuttonActionPerformed
  {//GEN-HEADEREND:event_closebuttonActionPerformed
    setVisible( false );
    dispose();
  }//GEN-LAST:event_closebuttonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel bottompanel;
  private javax.swing.JButton closebutton;
  private javax.swing.JLabel imagelabel;
  private javax.swing.JScrollPane scrollpane;
  // End of variables declaration//GEN-END:variables
}
