/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

import java.awt.*;
import java.util.*;
import java.util.List;
import org.qyouti.templates.*;

/**
 *
 * @author jon
 */
public class QuestionAllEditDialog
        extends javax.swing.JDialog
{
  ArrayList<ItemTemplate> templates = new ArrayList<ItemTemplate>();
  QyoutiFrame parent;
  
  /**
   * Creates new form QuestionEditDialog
   */
  public QuestionAllEditDialog( QyoutiFrame parent, boolean modal )
  {
    super( parent, modal );
    this.parent = parent;
    initComponents();
  }

  public void addTemplate( ItemTemplate template )
  {
    templates.add( template );
    centrepanel.add( template.getComponent() );
    this.pack();
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    scrollpane = new javax.swing.JScrollPane();
    centrepanel = new javax.swing.JPanel();
    bottompanel = new javax.swing.JPanel();
    savebutton = new javax.swing.JButton();
    cancelbutton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Question Edit");

    scrollpane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    scrollpane.setMinimumSize(new java.awt.Dimension(100, 100));

    centrepanel.setLayout(new java.awt.GridLayout(0, 1));
    scrollpane.setViewportView(centrepanel);

    getContentPane().add(scrollpane, java.awt.BorderLayout.CENTER);

    savebutton.setText("Save");
    savebutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        savebuttonActionPerformed(evt);
      }
    });
    bottompanel.add(savebutton);

    cancelbutton.setText("Cancel");
    cancelbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelbuttonActionPerformed(evt);
      }
    });
    bottompanel.add(cancelbutton);

    getContentPane().add(bottompanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelbuttonActionPerformed
  {//GEN-HEADEREND:event_cancelbuttonActionPerformed
    // TODO add your handling code here:
    this.setVisible( false );
    this.dispose();
  }//GEN-LAST:event_cancelbuttonActionPerformed

  private void savebuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_savebuttonActionPerformed
  {//GEN-HEADEREND:event_savebuttonActionPerformed
    ItemTemplate template;
    for ( int i=0; i< templates.size(); i++ )
    {
      template = templates.get( i );
      if ( template.isChanged() )
      {
        template.store();
      }
    }
    parent.questionEditStored();
    this.setVisible( false );
    this.dispose();
  }//GEN-LAST:event_savebuttonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel bottompanel;
  private javax.swing.JButton cancelbutton;
  private javax.swing.JPanel centrepanel;
  private javax.swing.JButton savebutton;
  private javax.swing.JScrollPane scrollpane;
  // End of variables declaration//GEN-END:variables
}
