/*
 *
 * Copyright 2010 Leeds Metropolitan University
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may 
 * not use this file except in compliance with the License. You may obtain 
 * a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License. 
 *
 *
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QyoutiQuestionDialog.java
 *
 * Created on 08-Apr-2010, 22:03:11
 */
package org.qyouti;

import javax.swing.JScrollPane;
import org.apache.batik.swing.JSVGCanvas;
import org.qyouti.qti1.element.QTIElementItem;
import org.qyouti.qti1.gui.*;
import org.qyouti.qti1.gui.QTIItemRenderer;
import org.w3c.dom.svg.SVGDocument;

/**
 *
 * @author jon
 */
public class QyoutiQuestionDialog extends javax.swing.JDialog
{
    QTIElementItem item = null;
    QTIItemRenderer renderer = null;

    /** Creates new form QyoutiQuestionDialog */
    public QyoutiQuestionDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        getRootPane().setDefaultButton(closeButton);
        initComponents();
    }

    public void setItem( QTIElementItem item )
    {
        this.item = item;

        renderer = new QTIItemRenderer( item );
        if ( renderer != null )
        {
            JSVGCanvas canvas = new JSVGCanvas();
            canvas.setSVGDocument( (SVGDocument) renderer.getSVGDocument());
            scrollpane.setViewportView( canvas );
        }
    }

    public JScrollPane getScrollPane()
    {
        return scrollpane;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane = new javax.swing.JScrollPane();
        bottompanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.BorderLayout(1, 0));

        scrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollpane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollpane.setName("scrollpane"); // NOI18N
        getContentPane().add(scrollpane, java.awt.BorderLayout.CENTER);

        bottompanel.setName("bottompanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.qyouti.QyoutiApp.class).getContext().getResourceMap(QyoutiQuestionDialog.class);
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        bottompanel.add(closeButton);

        getContentPane().add(bottompanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottompanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane scrollpane;
    // End of variables declaration//GEN-END:variables
}
