/*
 *
 * Copyright 2010 Leeds Metropolitan University
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may 
 * not use this file except in compliance with the License. You may obtain 
 * a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License. 
 *
 *
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QyoutiQuestionDialog.java
 *
 * Created on 08-Apr-2010, 22:03:11
 */
package org.qyouti;

import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import org.apache.batik.dom.util.DOMUtilities;
import org.apache.batik.swing.JSVGCanvas;
import org.qyouti.qti1.element.QTIElementItem;
import org.qyouti.qti1.gui.*;
import org.qyouti.qti1.gui.QTIItemRenderer;
import org.w3c.dom.svg.SVGDocument;

/**
 *
 * @author jon
 */
public class QyoutiQuestionDialog extends javax.swing.JDialog
{
    QTIElementItem item = null;
    QTIItemRenderer renderer = null;
    URI examfolderuri;

    /** Creates new form QyoutiQuestionDialog
     * @param parent
     * @param modal 
     */
    public QyoutiQuestionDialog(java.awt.Frame parent, boolean modal, URI examfolderuri)
    {
        super(parent, modal);
        this.examfolderuri = examfolderuri;
        getRootPane().setDefaultButton(closeButton);
        initComponents();
        
    }

    public void setItem( QTIElementItem item )
    {
        this.item = item;

        renderer = new QTIItemRenderer( examfolderuri, item );
        if ( renderer == null )
        {
            previewcanvas.setSVGDocument(null);
            return;
        }

        String strsvg = DOMUtilities.getXML(renderer.getPreviewSVGDocument().getDocumentElement());

        {
            FileWriter writer = null;
            try
            {
                writer = new FileWriter("/home/jon/Desktop/debug.svg");
                writer.write("<?xml version=\"1.0\"?>\n");
                writer.write(strsvg);
            } catch (IOException ex)
            {
                Logger.getLogger(QyoutiQuestionDialog.class.getName()).log(Level.SEVERE, null, ex);
            } finally
            {
                try
                {
                    writer.close();
                } catch (IOException ex)
                {
                    Logger.getLogger(QyoutiQuestionDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        System.out.println( "=====================================" );
        System.out.println( strsvg );
        System.out.println( "=====================================" );
        previewcanvas.setSVGDocument( (SVGDocument) renderer.getPreviewSVGDocument());
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toppanel = new javax.swing.JPanel();
        centrepanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        previewcanvas = new org.apache.batik.swing.JSVGCanvas();
        bottompanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.BorderLayout(1, 0));

        toppanel.setName("toppanel"); // NOI18N
        toppanel.setLayout(new java.awt.BorderLayout());

        centrepanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        centrepanel.setName("centrepanel"); // NOI18N
        centrepanel.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        previewcanvas.setEnableRotateInteractor(false);
        previewcanvas.setName("previewcanvas"); // NOI18N
        previewcanvas.setRecenterOnResize(false);
        jScrollPane1.setViewportView(previewcanvas);

        centrepanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        toppanel.add(centrepanel, java.awt.BorderLayout.CENTER);

        bottompanel.setName("bottompanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.qyouti.QyoutiApp.class).getContext().getResourceMap(QyoutiQuestionDialog.class);
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        bottompanel.add(closeButton);

        toppanel.add(bottompanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(toppanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottompanel;
    private javax.swing.JPanel centrepanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private org.apache.batik.swing.JSVGCanvas previewcanvas;
    private javax.swing.JPanel toppanel;
    // End of variables declaration//GEN-END:variables
}
