/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

import java.awt.FlowLayout;
import java.awt.Frame;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.bouncycastle.openpgp.PGPPublicKey;
import org.quipto.compositefile.EncryptedCompositeFileUser;
import org.qyouti.crypto.CryptographyManager;
import org.qyouti.data.KeyData;

/**
 *
 * @author maber01
 */
public class TeamAddMemberDialog
        extends javax.swing.JDialog
{
  CryptographyManager cryptoman;
  EncryptedCompositeFileUser user;

  private static final DateFormat df = new SimpleDateFormat( "HH:mm dd/MMM/yyyy" );

  private KeyData publicentries;
  
  private PGPPublicKey selectedkey=null;
  private boolean controller=false;
  
  /**
   * Creates new form IdentityDialog
   * @param parent
   * @param cryptoman
   */
  public TeamAddMemberDialog(Frame parent, CryptographyManager cryptoman )
  {
    super(parent, true);
    this.cryptoman = cryptoman;
    publicentries = new KeyData( cryptoman );
    initComponents();    
    trustedpublickeylist.setModel(publicentries);
    updateFields();
  }

  public PGPPublicKey getSelectedPublicKey()
  {
    return selectedkey;
  }
  public boolean isSelectedPublicKeyController()
  {
    return controller;
  }

//  private void sortEntries()
//  {
//    entries.sort( new Comparator<Entry>() {
//      @Override
//      public int compare(Entry o1, Entry o2)
//      {
//        long da = 0L;
//        long db = 0L;
//        if ( o1.creationdate != null )
//          da = o1.creationdate.getTime();
//        if ( o2.creationdate != null )
//          db = o2.creationdate.getTime();
//        if ( da < db ) return -1;
//        if ( da > db ) return 1;
//        return 0;
//      }
//    } );
//  }
  
 
  private final void updateButtons()
  {
    int selecteditem;
    selecteditem = trustedpublickeylist.getSelectedIndex();
    addcontrollerbutton.setEnabled( selecteditem >= 0 );
  }
  
  private final void updateFields()
  {
    publicentries.clear();
    
    if ( cryptoman.personalKeyStoreFileExists() )
    {
      PGPPublicKey[] pubkeys;
      pubkeys = cryptoman.getTrustedPublicKeys();
      for ( PGPPublicKey k : pubkeys )
        publicentries.addKey( k );
    }

    updateSelectedTrustedKeyPane();
    updateButtons();
  }

  private void updateSelectedTrustedKeyPane()
  {
    trustedsplitpane.setRightComponent(null);
    int selected = trustedpublickeylist.getSelectedIndex();
    if ( selected >= 0 )
    {
      PGPPublicKey puck = publicentries.getKeyAt(selected);
      PublicKeyPanel pukpanel = new PublicKeyPanel( puck );
      trustedsplitpane.setRightComponent( pukpanel );
    }    
    else
    {
      JPanel blank = new JPanel();
      blank.setLayout( new FlowLayout() );
      blank.add( new JLabel( cryptoman.personalKeyStoreFileExists()?"Create or select a key pair.":"No personal key store exists." ) );
      trustedsplitpane.setRightComponent( blank ); 
      return;
    }
  }

  private void addMember( boolean controller )
  {
    int selected = trustedpublickeylist.getSelectedIndex();
    if ( selected < 0 )
    {
      JOptionPane.showMessageDialog( rootPane, "Select a public key from the list first." );
      return;
    }
    
    selectedkey = publicentries.getKeyAt( selected );
    this.controller = controller;
    dispose();
  }
  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel2 = new javax.swing.JLabel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jPanel1 = new javax.swing.JPanel();
    tabbedpane = new javax.swing.JTabbedPane();
    trustedsplitpane = new javax.swing.JSplitPane();
    jScrollPane2 = new javax.swing.JScrollPane();
    trustedpublickeylist = new javax.swing.JList<>();
    jPanel2 = new javax.swing.JPanel();
    addcontrollerbutton = new javax.swing.JButton();
    addmemberbutton = new javax.swing.JButton();
    closebutton = new javax.swing.JButton();

    jLabel2.setText("jLabel2");

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 18, 8, 18));

    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setText("Select the key you want to add to the team.  Adding the key as a team controller will allow the owner of the key to add other keys.  To prevent that add the key as a team member.\n");
    jTextArea1.setWrapStyleWord(true);
    jTextArea1.setOpaque(false);
    jScrollPane3.setViewportView(jTextArea1);

    getContentPane().add(jScrollPane3, java.awt.BorderLayout.NORTH);

    jPanel1.setMinimumSize(new java.awt.Dimension(650, 400));
    jPanel1.setPreferredSize(new java.awt.Dimension(650, 400));
    jPanel1.setLayout(new java.awt.BorderLayout());

    tabbedpane.setMinimumSize(new java.awt.Dimension(500, 300));
    tabbedpane.setPreferredSize(new java.awt.Dimension(500, 300));
    tabbedpane.addChangeListener(new javax.swing.event.ChangeListener()
    {
      public void stateChanged(javax.swing.event.ChangeEvent evt)
      {
        tabbedpaneStateChanged(evt);
      }
    });
    tabbedpane.addPropertyChangeListener(new java.beans.PropertyChangeListener()
    {
      public void propertyChange(java.beans.PropertyChangeEvent evt)
      {
        tabbedpanePropertyChange(evt);
      }
    });

    trustedsplitpane.setDividerLocation(200);
    trustedsplitpane.setDividerSize(10);
    trustedsplitpane.setResizeWeight(0.5);

    trustedpublickeylist.setModel(new javax.swing.AbstractListModel<String>()
    {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    trustedpublickeylist.addListSelectionListener(new javax.swing.event.ListSelectionListener()
    {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt)
      {
        trustedpublickeylistValueChanged(evt);
      }
    });
    jScrollPane2.setViewportView(trustedpublickeylist);

    trustedsplitpane.setLeftComponent(jScrollPane2);

    tabbedpane.addTab("Trusted Keys", trustedsplitpane);

    jPanel1.add(tabbedpane, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    addcontrollerbutton.setText("Add Team Controller");
    addcontrollerbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        addcontrollerbuttonActionPerformed(evt);
      }
    });
    jPanel2.add(addcontrollerbutton);

    addmemberbutton.setText("Add Team Member");
    addmemberbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        addmemberbuttonActionPerformed(evt);
      }
    });
    jPanel2.add(addmemberbutton);

    closebutton.setText("Cancel");
    closebutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        closebuttonActionPerformed(evt);
      }
    });
    jPanel2.add(closebutton);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void closebuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closebuttonActionPerformed
  {//GEN-HEADEREND:event_closebuttonActionPerformed
    selectedkey = null;
    dispose();
  }//GEN-LAST:event_closebuttonActionPerformed

  private void addcontrollerbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addcontrollerbuttonActionPerformed
  {//GEN-HEADEREND:event_addcontrollerbuttonActionPerformed
    
    addMember( true );
    
  }//GEN-LAST:event_addcontrollerbuttonActionPerformed

  private void trustedpublickeylistValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_trustedpublickeylistValueChanged
  {//GEN-HEADEREND:event_trustedpublickeylistValueChanged
    if ( evt.getValueIsAdjusting() ) return;
    System.out.println( "List selection event." );
    updateSelectedTrustedKeyPane();
    updateButtons();
  }//GEN-LAST:event_trustedpublickeylistValueChanged

  private void tabbedpanePropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_tabbedpanePropertyChange
  {//GEN-HEADEREND:event_tabbedpanePropertyChange
    // TODO add your handling code here:
  }//GEN-LAST:event_tabbedpanePropertyChange

  private void tabbedpaneStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_tabbedpaneStateChanged
  {//GEN-HEADEREND:event_tabbedpaneStateChanged
    updateButtons();
  }//GEN-LAST:event_tabbedpaneStateChanged

  private void addmemberbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addmemberbuttonActionPerformed
  {//GEN-HEADEREND:event_addmemberbuttonActionPerformed
    addMember( false );
  }//GEN-LAST:event_addmemberbuttonActionPerformed

  

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addcontrollerbutton;
  private javax.swing.JButton addmemberbutton;
  private javax.swing.JButton closebutton;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTabbedPane tabbedpane;
  private javax.swing.JList<String> trustedpublickeylist;
  private javax.swing.JSplitPane trustedsplitpane;
  // End of variables declaration//GEN-END:variables
}
