/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import org.bouncycastle.openpgp.PGPPublicKey;
import org.bouncycastle.openpgp.PGPSecretKey;
import org.quipto.compositefile.EncryptedCompositeFileUser;
import org.qyouti.crypto.CryptographyManager;
import org.qyouti.data.KeyData;

/**
 *
 * @author maber01
 */
public class TeamDialog
        extends javax.swing.JDialog
{
  CryptographyManager cryptoman;
  EncryptedCompositeFileUser user;

  private static final DateFormat df = new SimpleDateFormat( "HH:mm dd/MMM/yyyy" );

  private KeyData publicentries;
  
  /**
   * Creates new form IdentityDialog
   * @param parent
   * @param cryptoman
   */
  public TeamDialog(Frame parent, CryptographyManager cryptoman )
  {
    super(parent, true);
    this.setTitle("Qyouti - Manage Team Key Store");
    this.cryptoman = cryptoman;
    publicentries = new KeyData( cryptoman );
    initComponents();    
    trustedpublickeylist.setModel(publicentries);
    jTree1.setModel( cryptoman.getTeamTreeModel() );
    updateFields();
  }


//  private void sortEntries()
//  {
//    entries.sort( new Comparator<Entry>() {
//      @Override
//      public int compare(Entry o1, Entry o2)
//      {
//        long da = 0L;
//        long db = 0L;
//        if ( o1.creationdate != null )
//          da = o1.creationdate.getTime();
//        if ( o2.creationdate != null )
//          db = o2.creationdate.getTime();
//        if ( da < db ) return -1;
//        if ( da > db ) return 1;
//        return 0;
//      }
//    } );
//  }
  
 
  private final void updateButtons()
  {
    int selectedpane = tabbedpane.getSelectedIndex();
    int selecteditem=-1;
    if ( selectedpane == 1 )
      selecteditem = trustedpublickeylist.getSelectedIndex();
    addbutton.setEnabled( true  );
    endorsebutton.setEnabled( selecteditem >= 0 );
    deletebutton.setEnabled( selecteditem >= 0 );
  }
  
  private final void updateFields()
  {
    publicentries.clear();
    
    PGPPublicKey[] pubkeys;
    pubkeys = cryptoman.getTeamPublicKeys();
    for ( PGPPublicKey k : pubkeys )
      publicentries.addKey( k );

    keystorelabel.setText( cryptoman.getTeamKeyStoreFile().getAbsolutePath() );
    updateSelectedTrustedKeyPane();
    updateButtons();
  }

  private void updateSelectedTrustedKeyPane()
  {
    trustedsplitpane.setRightComponent(null);
    int selected = trustedpublickeylist.getSelectedIndex();
    if ( selected >= 0 )
    {
      PGPPublicKey puck = publicentries.getKeyAt(selected);
      PublicKeyPanel pukpanel = new PublicKeyPanel( cryptoman, puck );
      trustedsplitpane.setRightComponent( pukpanel );
    }    
    else
    {
      JPanel blank = new JPanel();
      blank.setLayout( new FlowLayout() );
      blank.add( new JLabel( cryptoman.personalKeyStoreFileExists()?"Create or select a key pair.":"No personal key store exists." ) );
      trustedsplitpane.setRightComponent( blank ); 
      return;
    }
  }

  
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel2 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    keystorelabel = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    tabbedpane = new javax.swing.JTabbedPane();
    teammapsplitpane = new javax.swing.JSplitPane();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTree1 = new javax.swing.JTree();
    jPanel4 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jPanel5 = new javax.swing.JPanel();
    jPanel6 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    trustedsplitpane = new javax.swing.JSplitPane();
    jScrollPane2 = new javax.swing.JScrollPane();
    trustedpublickeylist = new javax.swing.JList<>();
    jPanel2 = new javax.swing.JPanel();
    addbutton = new javax.swing.JButton();
    endorsebutton = new javax.swing.JButton();
    deletebutton = new javax.swing.JButton();
    closebutton = new javax.swing.JButton();

    jLabel2.setText("jLabel2");

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel1.setText("Team Key Store:");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(keystorelabel, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(keystorelabel))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

    jPanel1.setMinimumSize(new java.awt.Dimension(650, 400));
    jPanel1.setPreferredSize(new java.awt.Dimension(650, 400));
    jPanel1.setLayout(new java.awt.BorderLayout());

    tabbedpane.setMinimumSize(new java.awt.Dimension(500, 300));
    tabbedpane.setPreferredSize(new java.awt.Dimension(500, 300));
    tabbedpane.addChangeListener(new javax.swing.event.ChangeListener()
    {
      public void stateChanged(javax.swing.event.ChangeEvent evt)
      {
        tabbedpaneStateChanged(evt);
      }
    });
    tabbedpane.addPropertyChangeListener(new java.beans.PropertyChangeListener()
    {
      public void propertyChange(java.beans.PropertyChangeEvent evt)
      {
        tabbedpanePropertyChange(evt);
      }
    });

    teammapsplitpane.setDividerLocation(500);
    teammapsplitpane.setDividerSize(10);
    teammapsplitpane.setResizeWeight(0.5);

    jScrollPane3.setViewportView(jTree1);

    teammapsplitpane.setLeftComponent(jScrollPane3);

    jPanel4.setLayout(new java.awt.BorderLayout());

    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
    jTextArea1.setLineWrap(true);
    jTextArea1.setRows(5);
    jTextArea1.setText("This panel is under development. It will give information about the node selected in the tree diagram. Missing signatures will be highlighted and it will be possible to promote/demote a key to/from controller.\n\nAt present a controller key is indicated with a folder icon whereas an ordinary member key is indicated with a file icon.\n");
    jTextArea1.setWrapStyleWord(true);
    jTextArea1.setOpaque(false);
    jScrollPane1.setViewportView(jTextArea1);

    jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

    jPanel6.setLayout(new java.awt.GridBagLayout());

    jButton1.setText("Promote");
    jButton1.setEnabled(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    jPanel6.add(jButton1, gridBagConstraints);

    jButton2.setText("Demote");
    jButton2.setEnabled(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
    jPanel6.add(jButton2, gridBagConstraints);

    jPanel5.add(jPanel6);

    jPanel4.add(jPanel5, java.awt.BorderLayout.WEST);

    teammapsplitpane.setRightComponent(jPanel4);

    tabbedpane.addTab("Team Trust Map", teammapsplitpane);

    trustedsplitpane.setDividerLocation(200);
    trustedsplitpane.setDividerSize(10);
    trustedsplitpane.setResizeWeight(0.5);

    trustedpublickeylist.setModel(new javax.swing.AbstractListModel<String>()
    {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public String getElementAt(int i) { return strings[i]; }
    });
    trustedpublickeylist.addListSelectionListener(new javax.swing.event.ListSelectionListener()
    {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt)
      {
        trustedpublickeylistValueChanged(evt);
      }
    });
    jScrollPane2.setViewportView(trustedpublickeylist);

    trustedsplitpane.setLeftComponent(jScrollPane2);

    tabbedpane.addTab("Team Public Keys", trustedsplitpane);

    jPanel1.add(tabbedpane, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    addbutton.setText("Add Key...");
    addbutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        addbuttonActionPerformed(evt);
      }
    });
    jPanel2.add(addbutton);

    endorsebutton.setText("Add Signature to Key");
    endorsebutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        endorsebuttonActionPerformed(evt);
      }
    });
    jPanel2.add(endorsebutton);

    deletebutton.setText("Delete...");
    deletebutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        deletebuttonActionPerformed(evt);
      }
    });
    jPanel2.add(deletebutton);

    closebutton.setText("Close");
    closebutton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        closebuttonActionPerformed(evt);
      }
    });
    jPanel2.add(closebutton);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void closebuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closebuttonActionPerformed
  {//GEN-HEADEREND:event_closebuttonActionPerformed
    dispose();
  }//GEN-LAST:event_closebuttonActionPerformed

  private void addbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addbuttonActionPerformed
  {//GEN-HEADEREND:event_addbuttonActionPerformed
    
    TeamAddMemberDialog dialog = new TeamAddMemberDialog( (Frame)getParent(), cryptoman );
    dialog.setVisible( true );
    PGPPublicKey selectedkey = dialog.getSelectedPublicKey();
    if ( selectedkey == null )
      return;
    
    if ( !cryptoman.isTeamController() )
    {
      JOptionPane.showMessageDialog( rootPane, "Your personal key lacks controller access to the team. So, it is not possible edit the team." );
      return;
    }
    
    if ( !cryptoman.addPublicKeyToTeam(selectedkey, dialog.isSelectedPublicKeyController() ) )
      JOptionPane.showMessageDialog( rootPane, "A technical problem occured attempting to add the key to the team." );      
    
    updateFields();
    updateButtons();
  }//GEN-LAST:event_addbuttonActionPerformed

  private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deletebuttonActionPerformed
  {//GEN-HEADEREND:event_deletebuttonActionPerformed
    
    int selected = trustedpublickeylist.getSelectedIndex();
    if ( selected < 0 )
    {
      JOptionPane.showMessageDialog( rootPane, "No key pair is selected." );
      return;
    }
    
    if ( JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog( rootPane, 
            "If you delete the public key from the team, data signed \n" +
            "by the owner of it will no longer be accepted as authentic \n" +
            "by other team members. Also, data saved by team members will \n" +
            "not be accessible by the owner of the key.\n\n" +
            "Are you sure you want to delete the public key?",
            "Delete Public Key",
            JOptionPane.YES_NO_OPTION ) )
      return;
    
    JOptionPane.showMessageDialog( rootPane, "Removing keys from the team is not yet implemented." );
    //cryptoman.removePublicKeyFromTeam( publicentries.getKeyAt( selected ) );
//      JOptionPane.showMessageDialog( rootPane, "There was a technical fault attempting to delete your key pair." );
    updateFields();
    
  }//GEN-LAST:event_deletebuttonActionPerformed

  private void trustedpublickeylistValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_trustedpublickeylistValueChanged
  {//GEN-HEADEREND:event_trustedpublickeylistValueChanged
    if ( evt.getValueIsAdjusting() ) return;
    System.out.println( "List selection event." );
    updateSelectedTrustedKeyPane();
    updateButtons();
  }//GEN-LAST:event_trustedpublickeylistValueChanged

  private void tabbedpanePropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_tabbedpanePropertyChange
  {//GEN-HEADEREND:event_tabbedpanePropertyChange
    // TODO add your handling code here:
  }//GEN-LAST:event_tabbedpanePropertyChange

  private void tabbedpaneStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_tabbedpaneStateChanged
  {//GEN-HEADEREND:event_tabbedpaneStateChanged
    updateButtons();
  }//GEN-LAST:event_tabbedpaneStateChanged

  private void endorsebuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_endorsebuttonActionPerformed
  {//GEN-HEADEREND:event_endorsebuttonActionPerformed
    
    int selected = trustedpublickeylist.getSelectedIndex();
    if ( selected < 0 )
    {
      JOptionPane.showMessageDialog( rootPane, "No key pair is selected." );
      return;
    }    

    if ( !cryptoman.endorsePublicKeyInTeam( publicentries.getKeyAt( selected ) ) )
      JOptionPane.showMessageDialog( rootPane, "Unable to endorse the selected public key." );    
  }//GEN-LAST:event_endorsebuttonActionPerformed

  
  private char[] promptForPassword()
  {
    JPanel panel = new JPanel();
    JLabel label = new JLabel("Enter a password:");
    JPasswordField pass = new JPasswordField();
    panel.setLayout(new FlowLayout() );
    pass.setMinimumSize( new Dimension(200,30) );
    pass.setPreferredSize( pass.getMinimumSize() );
    pass.setSize( pass.getMinimumSize() );
    panel.add(label);
    panel.add(pass);
    panel.doLayout();
    String[] options = new String[]{"O.K.", "Cancel"};
    int option = JOptionPane.showOptionDialog(null, panel, "Enter Password",
                             JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                             null, options, options[1]);
    if(option == 0) // pressing OK button
      return pass.getPassword();
    return null;
  }
  
 


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addbutton;
  private javax.swing.JButton closebutton;
  private javax.swing.JButton deletebutton;
  private javax.swing.JButton endorsebutton;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTree jTree1;
  private javax.swing.JLabel keystorelabel;
  private javax.swing.JTabbedPane tabbedpane;
  private javax.swing.JSplitPane teammapsplitpane;
  private javax.swing.JList<String> trustedpublickeylist;
  private javax.swing.JSplitPane trustedsplitpane;
  // End of variables declaration//GEN-END:variables
}
