/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.qyouti;

/**
 *
 * @author jon
 */
public class UserRenderDialog
        extends javax.swing.JDialog
{

  /**
   * Creates new form UserRenderDialog
   */
  public UserRenderDialog( java.awt.Frame parent, boolean modal )
  {
    super( parent, modal );
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    mainpanel = new javax.swing.JPanel();
    bigpinkcheckbox = new javax.swing.JCheckBox();
    serifcheckbox = new javax.swing.JCheckBox();
    fontdizelabel = new javax.swing.JLabel();
    panel1 = new javax.swing.JPanel();
    jRadioButton1 = new javax.swing.JRadioButton();
    jTextField1 = new javax.swing.JTextField();
    jRadioButton2 = new javax.swing.JRadioButton();
    jColorChooser1 = new javax.swing.JColorChooser();
    bottompanel = new javax.swing.JPanel();
    applybutton = new javax.swing.JButton();
    clearbutton = new javax.swing.JButton();
    cancelbutton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    mainpanel.setLayout(new java.awt.GridBagLayout());

    bigpinkcheckbox.setText("Enlarge Pink Box");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    mainpanel.add(bigpinkcheckbox, gridBagConstraints);

    serifcheckbox.setText("Use Serif Font");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    mainpanel.add(serifcheckbox, gridBagConstraints);

    fontdizelabel.setText("Font Size:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    mainpanel.add(fontdizelabel, gridBagConstraints);

    panel1.setLayout(new java.awt.GridBagLayout());

    jRadioButton1.setText("This Size:");
    jRadioButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jRadioButton1ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    panel1.add(jRadioButton1, gridBagConstraints);

    jTextField1.setColumns(10);
    jTextField1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jTextField1ActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 66;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 27, 0, 0);
    panel1.add(jTextField1, gridBagConstraints);

    jRadioButton2.setText("Use Standard");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    panel1.add(jRadioButton2, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 3;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    mainpanel.add(panel1, gridBagConstraints);

    jColorChooser1.setBorder(javax.swing.BorderFactory.createTitledBorder("Page Background Colour"));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    mainpanel.add(jColorChooser1, gridBagConstraints);

    getContentPane().add(mainpanel, java.awt.BorderLayout.CENTER);

    applybutton.setText("Apply");
    bottompanel.add(applybutton);

    clearbutton.setText("Clear");
    bottompanel.add(clearbutton);

    cancelbutton.setText("Cancel");
    bottompanel.add(cancelbutton);

    getContentPane().add(bottompanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
  {//GEN-HEADEREND:event_jTextField1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField1ActionPerformed

  private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
  {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jRadioButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main( String args[] )
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
              getInstalledLookAndFeels() )
      {
        if ( "Nimbus".equals( info.getName() ) )
        {
          javax.swing.UIManager.setLookAndFeel( info.getClassName() );
          break;
        }
      }
    }
    catch ( ClassNotFoundException ex )
    {
      java.util.logging.Logger.getLogger( UserRenderDialog.class.getName() ).
              log( java.util.logging.Level.SEVERE, null, ex );
    }
    catch ( InstantiationException ex )
    {
      java.util.logging.Logger.getLogger( UserRenderDialog.class.getName() ).
              log( java.util.logging.Level.SEVERE, null, ex );
    }
    catch ( IllegalAccessException ex )
    {
      java.util.logging.Logger.getLogger( UserRenderDialog.class.getName() ).
              log( java.util.logging.Level.SEVERE, null, ex );
    }
    catch ( javax.swing.UnsupportedLookAndFeelException ex )
    {
      java.util.logging.Logger.getLogger( UserRenderDialog.class.getName() ).
              log( java.util.logging.Level.SEVERE, null, ex );
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater( new Runnable()
    {
      public void run()
      {
        UserRenderDialog dialog = new UserRenderDialog( new javax.swing.JFrame(), true );
        dialog.addWindowListener( new java.awt.event.WindowAdapter()
        {
          @Override
          public void windowClosing( java.awt.event.WindowEvent e )
          {
            System.exit( 0 );
          }
        } );
        dialog.setVisible( true );
      }
    } );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton applybutton;
  private javax.swing.JCheckBox bigpinkcheckbox;
  private javax.swing.JPanel bottompanel;
  private javax.swing.JButton cancelbutton;
  private javax.swing.JButton clearbutton;
  private javax.swing.JLabel fontdizelabel;
  private javax.swing.JColorChooser jColorChooser1;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JPanel mainpanel;
  private javax.swing.JPanel panel1;
  private javax.swing.JCheckBox serifcheckbox;
  // End of variables declaration//GEN-END:variables
}
