/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExamOptionsDialog.java
 *
 * Created on Nov 3, 2010, 8:56:06 AM
 */

package org.qyouti.dialog;

import org.qyouti.data.ExaminationData;

/**
 *
 * @author jon
 */
public class ExamOptionsDialog extends javax.swing.JDialog {

    boolean cancelled=true;
    ExaminationData exam;
    
    /** Creates new form ExamOptionsDialog */
    public ExamOptionsDialog(java.awt.Frame parent, boolean modal, ExaminationData exam ) {
        super(parent, modal);
        this.exam = exam;
        initComponents();

        coversheetCheckbox.setSelected(exam.getQTIRenderBooleanOption("cover_sheet"));
        doublesidedCheckbox.setSelected(exam.getQTIRenderBooleanOption("double_sided"));
        ignoreflowCheckbox.setSelected(exam.getQTIRenderBooleanOption("ignore_flow"));
        questiontitleCheckbox.setSelected(exam.getQTIRenderBooleanOption("question_titles"));
        questionmetricsCheckbox.setSelected(exam.getQTIRenderBooleanOption("question_metrics_qr"));
        headerTextField.setText( exam.getQTIRenderOption( "header" ) );
        nameinfooterCheckbox.setSelected(  exam.getQTIRenderBooleanOption("name_in_footer"));
        idinfooterCheckbox.setSelected(  exam.getQTIRenderBooleanOption("id_in_footer"));
    }

    public boolean wasCancelled()
    {
      return cancelled;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    coversheetCheckbox = new javax.swing.JCheckBox();
    doublesidedCheckbox = new javax.swing.JCheckBox();
    ignoreflowCheckbox = new javax.swing.JCheckBox();
    questiontitleCheckbox = new javax.swing.JCheckBox();
    questionmetricsCheckbox = new javax.swing.JCheckBox();
    jPanel3 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    headerTextField = new javax.swing.JTextField();
    nameinfooterCheckbox = new javax.swing.JCheckBox();
    idinfooterCheckbox = new javax.swing.JCheckBox();
    jPanel2 = new javax.swing.JPanel();
    applyButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setName("Form"); // NOI18N

    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    jPanel1.setName("jPanel1"); // NOI18N
    jPanel1.setLayout(new java.awt.GridLayout(0, 1));

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.qyouti.QyoutiApp.class).getContext().getResourceMap(ExamOptionsDialog.class);
    coversheetCheckbox.setText(resourceMap.getString("coversheetCheckbox.text")); // NOI18N
    coversheetCheckbox.setName("coversheetCheckbox"); // NOI18N
    jPanel1.add(coversheetCheckbox);

    doublesidedCheckbox.setText(resourceMap.getString("doublesidedCheckbox.text")); // NOI18N
    doublesidedCheckbox.setName("doublesidedCheckbox"); // NOI18N
    jPanel1.add(doublesidedCheckbox);

    ignoreflowCheckbox.setText(resourceMap.getString("ignoreflowCheckbox.text")); // NOI18N
    ignoreflowCheckbox.setName("ignoreflowCheckbox"); // NOI18N
    jPanel1.add(ignoreflowCheckbox);

    questiontitleCheckbox.setText(resourceMap.getString("questiontitleCheckbox.text")); // NOI18N
    questiontitleCheckbox.setName("questiontitleCheckbox"); // NOI18N
    jPanel1.add(questiontitleCheckbox);

    questionmetricsCheckbox.setText(resourceMap.getString("questionmetricsCheckbox.text")); // NOI18N
    questionmetricsCheckbox.setName("questionmetricsCheckbox"); // NOI18N
    jPanel1.add(questionmetricsCheckbox);

    jPanel3.setName("jPanel3"); // NOI18N
    jPanel3.setLayout(new java.awt.BorderLayout());

    jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
    jLabel1.setName("jLabel1"); // NOI18N
    jPanel3.add(jLabel1, java.awt.BorderLayout.WEST);

    headerTextField.setText(resourceMap.getString("headerTextField.text")); // NOI18N
    headerTextField.setName("headerTextField"); // NOI18N
    jPanel3.add(headerTextField, java.awt.BorderLayout.CENTER);

    jPanel1.add(jPanel3);

    nameinfooterCheckbox.setText(resourceMap.getString("nameinfooterCheckbox.text")); // NOI18N
    nameinfooterCheckbox.setName("nameinfooterCheckbox"); // NOI18N
    jPanel1.add(nameinfooterCheckbox);

    idinfooterCheckbox.setText(resourceMap.getString("idinfooterCheckbox.text")); // NOI18N
    idinfooterCheckbox.setName("idinfooterCheckbox"); // NOI18N
    jPanel1.add(idinfooterCheckbox);

    getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

    jPanel2.setName("jPanel2"); // NOI18N

    applyButton.setText(resourceMap.getString("applyButton.text")); // NOI18N
    applyButton.setName("applyButton"); // NOI18N
    applyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        applyButtonActionPerformed(evt);
      }
    });
    jPanel2.add(applyButton);

    cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
    cancelButton.setName("cancelButton"); // NOI18N
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    jPanel2.add(cancelButton);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
      // TODO add your handling code here:
      this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_applyButtonActionPerformed
    {//GEN-HEADEREND:event_applyButtonActionPerformed
      // TODO add your handling code here:
      cancelled=false;

      exam.setOption("cover_sheet", coversheetCheckbox.isSelected() );
      exam.setOption("ignore_flow", ignoreflowCheckbox.isSelected() );
      exam.setOption("question_titles", questiontitleCheckbox.isSelected() );
      exam.setOption("question_metrics_qr", questionmetricsCheckbox.isSelected() );
      exam.setOption("double_sided", doublesidedCheckbox.isSelected() );
      exam.setOption( "header", headerTextField.getText() );
      exam.setOption("name_in_footer", nameinfooterCheckbox.isSelected() );
      exam.setOption("id_in_footer", idinfooterCheckbox.isSelected() );
      this.dispose();
    }//GEN-LAST:event_applyButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton applyButton;
  private javax.swing.JButton cancelButton;
  private javax.swing.JCheckBox coversheetCheckbox;
  private javax.swing.JCheckBox doublesidedCheckbox;
  private javax.swing.JTextField headerTextField;
  private javax.swing.JCheckBox idinfooterCheckbox;
  private javax.swing.JCheckBox ignoreflowCheckbox;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JCheckBox nameinfooterCheckbox;
  private javax.swing.JCheckBox questionmetricsCheckbox;
  private javax.swing.JCheckBox questiontitleCheckbox;
  // End of variables declaration//GEN-END:variables

}
