/*
 *
 * Copyright 2010 Leeds Metropolitan University
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may 
 * not use this file except in compliance with the License. You may obtain 
 * a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License. 
 *
 *
 */



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewExamination.java
 *
 * Created on 05-Aug-2009, 14:15:18
 */

package org.qyouti.dialog;

import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jon
 */
public class NewExamination extends javax.swing.JDialog
{

  File appfolder;
  File examfolder;
  
  /** Creates new form NewExamination
   * @param parent
   * @param modal
   * @param appfolder
   */
    public NewExamination(java.awt.Frame parent, boolean modal, File appfolder)
    {
        super(parent, modal);
        this.appfolder = appfolder;
        initComponents();
    }

    public File getExamFolder()
    {
      return examfolder;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    createButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.qyouti.QyoutiApp.class).getContext().getResourceMap(NewExamination.class);
    setTitle(resourceMap.getString("Form.title")); // NOI18N
    setAlwaysOnTop(true);
    setModal(true);
    setName("Form"); // NOI18N
    setResizable(false);

    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 1, 1, 1));
    jPanel1.setName("jPanel1"); // NOI18N

    jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
    jLabel1.setName("jLabel1"); // NOI18N
    jPanel1.add(jLabel1);

    nameField.setText(resourceMap.getString("nameField.text")); // NOI18N
    nameField.setMinimumSize(new java.awt.Dimension(160, 24));
    nameField.setName("nameField"); // NOI18N
    nameField.setPreferredSize(new java.awt.Dimension(160, 24));
    jPanel1.add(nameField);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    jPanel2.setName("jPanel2"); // NOI18N

    createButton.setText(resourceMap.getString("createButton.text")); // NOI18N
    createButton.setName("createButton"); // NOI18N
    createButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        createButtonActionPerformed(evt);
      }
    });
    jPanel2.add(createButton);

    cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
    cancelButton.setName("cancelButton"); // NOI18N
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    jPanel2.add(cancelButton);

    getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
      // TODO add your handling code here:
      examfolder = null;
      dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_createButtonActionPerformed
    {//GEN-HEADEREND:event_createButtonActionPerformed
      // TODO add your handling code here:
      examfolder = null;

      if ( appfolder == null || !appfolder.exists() || !appfolder.isDirectory() )
      {
        JOptionPane.showMessageDialog(rootPane, "The application folder doesn't exist - technical error.");
        return;
      }

      String name = nameField.getText();
      if ( name == null || name.length() == 0 )
      {
        JOptionPane.showMessageDialog(rootPane, "You must enter an examination name.");
        return;
      }

      for ( int i=0; i<name.length(); i++ )
      {
        char c = name.charAt( i );
        if ( Character.isLetter( c ) || Character.isDigit( c ) || c == '_' )
          continue;

        JOptionPane.showMessageDialog( rootPane, "Examination name may only contain letters, numbers and the underscore character." );
        return;
      }

      File folder = new File( appfolder, name );
      if ( folder.exists() )
      {
        JOptionPane.showMessageDialog(rootPane, "A folder with your chosen name already exists.");
        return;
      }

      if ( !folder.mkdir() )
      {
        JOptionPane.showMessageDialog(rootPane, "It was not possible to create a folder for the exam - perhaps this is a file permissions issue.");
        return;
      }

      examfolder = folder;
      dispose();
    }//GEN-LAST:event_createButtonActionPerformed

    

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton createButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JTextField nameField;
  // End of variables declaration//GEN-END:variables

}
