/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestDialog.java
 *
 * Created on 27-Aug-2010, 09:52:49
 */

package org.qyouti.dialog;

/**
 *
 * @author jon
 */
public class TestDialog extends javax.swing.JDialog {

    TextPaneWrapper jTextPane1;
    
    /** Creates new form TestDialog */
    public TestDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        jTextPane1 = new TextPaneWrapper();
        jTextPane1.setText(
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf " +
                "as;lkdjf as;ldkfj a;sldkjf a;lsdkjf ;alskdjf ;alskdjf "
                ); // NOI18N
        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);
        
        System.out.println( "jpanel1 size " + jPanel1.getSize() );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.qyouti.QyoutiApp.class).getContext().getResourceMap(TestDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 100));
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TestDialog dialog = new TestDialog(new javax.swing.JFrame(), true);
                System.out.println( "jpanel1 size " + dialog.jPanel1.getSize() );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                System.out.println( "jpanel1 size " + dialog.jPanel1.getSize() );
                dialog.setVisible(true);
                System.out.println( "jpanel1 size " + dialog.jPanel1.getSize() );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
